# Usar la última versión de Ubuntu como base
FROM ubuntu:latest

# Actualizar los paquetes de APT y mejorar el software instalado
RUN apt-get update && apt-get upgrade -y

# Establecer el comando que se ejecutará cuando se inicie el contenedor
CMD echo "Hello, World!"
