services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end-image
    expose:
      - "9000"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end-image
    expose:
      - "5252"


  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-image
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend